### ISSUE TITLE
Apache2 on RPi

### ISSUE THREAD

**Issue by hitesh83** [dendory/Healthstone#5]
Hi,
on RPi Apache2 uses different config file. will you be able to help in installing Healthstone one RPi
while installing, I had supplied below mention path,  Hope thats correct.
`

/etc/apache2/
|-- apache2.conf
|       `--  ports.conf
|-- mods-enabled
|       |-- *.load
|       `-- *.conf
|-- conf-enabled
|       `-- *.conf
|-- sites-enabled
|       `-- *.conf
          `

I can view empty dashboard on http://192.168.0.250/healthstone  ,  but if I try to do any change in settings or while adding probe in settings, I get error **Could not add probe to the database.**  Also I had install linux client on ubuntu 16 , which runs the py file from cron every 1min. but I dont get any info on dashboard, when I run py file manually I get only below

```
Content-Type: text/html; charset=utf-8

Checking probes...
```

**Comment by dendory** [comment]
I'm guessing the Apache user you specified was probably wrong. Try this, assuming you installed it in `/use/share/healthstone`:

    chmod -R 777 /usr/share/healthstone/db
